
INSERT INTO tags VALUES(1, 'CC', 'coordinating conjunction', 'союз', 'FFFAFA');
INSERT INTO tags VALUES(2, 'CD', 'cardinal number', 'коичественное числительное', 'DCDCDC');
INSERT INTO tags VALUES(3, 'DT', 'determiner', 'артикль', 'FAF0E6');
INSERT INTO tags VALUES(4, 'EX', 'existential there', 'служебное there', 'FFDEAD');
INSERT INTO tags VALUES(5, 'FW', 'foreign word', 'иностранное слово', 'F0FFF0');
INSERT INTO tags VALUES(6, 'IN', 'preposition/subordinating conjunction', 'предлог (подчиненная связь);', 'E6E6FA');
INSERT INTO tags VALUES(7, 'JJ', 'adjective', 'прилагательное', 'FFE4E1');
INSERT INTO tags VALUES(8, 'JJR', 'adjective, comparative', 'сравнительное прилагательное', '696969');
INSERT INTO tags VALUES(9, 'JJS', 'adjective, superlative', 'превосходное прилагательное', '708090');
INSERT INTO tags VALUES(10, 'LS', 'list marker', 'прилагательное', 'BEBEBE');
INSERT INTO tags VALUES(11, 'MD', 'modal', 'прилагательное', '6495ED');
INSERT INTO tags VALUES(12, 'NN', 'noun, singular or mass', 'существительное единственного числа', '6A5ACD');
INSERT INTO tags VALUES(13, 'NNS', 'proper noun, singular', 'существительное множественного числа', '1E90FF');
INSERT INTO tags VALUES(14, 'NNP', 'proper noun, plural', 'собственное существительное в ед. числе', 'ADD8E6');
INSERT INTO tags VALUES(15, 'NNPS', 'proper noun, plural', 'собственное существительное во мн. числе', 'BOC4DE');
INSERT INTO tags VALUES(16, 'PDT', 'predeterminer', 'предетерминатор', '00CED1');
INSERT INTO tags VALUES(17, 'POS', 'possessive ending', 'притяжательное окончание', 'EOFFFF');
INSERT INTO tags VALUES(18, 'PRP', 'personal pronoun', 'личное местоимение', '66CDAA');
INSERT INTO tags VALUES(19, 'PRP$', 'possessive pronoun', 'притяжательное местоимение', '98FB98');
INSERT INTO tags VALUES(20, 'RB', 'adverb', 'наречие', '8FBC8F');
INSERT INTO tags VALUES(21, 'RBR', 'adverb, comparative', 'сравнительное наречие', '98FB98');
INSERT INTO tags VALUES(22, 'RBS', 'adverb, superlative', 'превосходное наречие', '8FBC8F');
INSERT INTO tags VALUES(23, 'RP', 'particle', 'частица', 'ADFF2F');
INSERT INTO tags VALUES(24, 'TO', 'to', 'to', 'FFD700');
INSERT INTO tags VALUES(25, 'UH', 'interjection', 'междометие', 'CD5C5C');
INSERT INTO tags VALUES(26, 'VB', 'verb, base form', 'глагол, базовая форма', 'CD853F');
INSERT INTO tags VALUES(27, 'VBD', 'verb, past tense', 'глагол, прошедшее время', 'FFC0CB');
INSERT INTO tags VALUES(28, 'VBG', 'verb, gerund/present participle', 'герундий, причастие наст. времени', 'CDC9C9');
INSERT INTO tags VALUES(29, 'VBN', 'verb, past participle', 'глагол, причастие прошедшего времени', 'FF8247');
INSERT INTO tags VALUES(30, 'VBP', 'verb, sing. present, non-3d', 'глагол настоящего времени', 'EED8AE');
INSERT INTO tags VALUES(31, 'VBZ', 'verb, 3rd person sing. present', 'глагол 3 лица', 'EE3B3B');
INSERT INTO tags VALUES(32, 'WDT', 'wh-determiner', 'wh-союз', 'CD00CD');
INSERT INTO tags VALUES(33, 'WP', 'wh-pronoun', 'wh-местоимение', '90EE90');
INSERT INTO tags VALUES(34, 'WP$', 'possessive wh-pronoun', 'притяжательно wh-местоимение', 'FFFF00');
INSERT INTO tags VALUES(35, 'WRB', 'wh-abverb', 'wh-наречие', '8B8B00');
INSERT INTO tags VALUES(36, '$', 'other tag', 'неизвестный', 'FFFF33');
